/// Flutter icons MyFlutterApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIconDashboard
///      fonts:
///       - asset: fonts/CustomIconDashboard.ttf
///
/// 
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class CustomIconDashboard {
  CustomIconDashboard._();

  static const _kFontFam = 'CustomIconDashboard';
  static const _kFontPkg = null;

  static const IconData gauge = IconData(0xf0e4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
